package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * BaixaReceber generated by hbm2java
 */
public class BaixaReceber  implements java.io.Serializable {


     private BaixaReceberId id;
     private TipoPagamento tipoPagamento;
     private TituloReceber tituloReceber;
     private BigDecimal valor;
     private String observacao;
     private Date dataPagamento;
     private Integer idusuario;
     private Date dataInclusao;
     private BigDecimal juros;

    public BaixaReceber() {
    }

	
    public BaixaReceber(BaixaReceberId id, TituloReceber tituloReceber) {
        this.id = id;
        this.tituloReceber = tituloReceber;
    }
    public BaixaReceber(BaixaReceberId id, TipoPagamento tipoPagamento, TituloReceber tituloReceber, BigDecimal valor, String observacao, Date dataPagamento, Integer idusuario, Date dataInclusao, BigDecimal juros) {
       this.id = id;
       this.tipoPagamento = tipoPagamento;
       this.tituloReceber = tituloReceber;
       this.valor = valor;
       this.observacao = observacao;
       this.dataPagamento = dataPagamento;
       this.idusuario = idusuario;
       this.dataInclusao = dataInclusao;
       this.juros = juros;
    }
   
    public BaixaReceberId getId() {
        return this.id;
    }
    
    public void setId(BaixaReceberId id) {
        this.id = id;
    }
    public TipoPagamento getTipoPagamento() {
        return this.tipoPagamento;
    }
    
    public void setTipoPagamento(TipoPagamento tipoPagamento) {
        this.tipoPagamento = tipoPagamento;
    }
    public TituloReceber getTituloReceber() {
        return this.tituloReceber;
    }
    
    public void setTituloReceber(TituloReceber tituloReceber) {
        this.tituloReceber = tituloReceber;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public Date getDataInclusao() {
        return this.dataInclusao;
    }
    
    public void setDataInclusao(Date dataInclusao) {
        this.dataInclusao = dataInclusao;
    }
    public BigDecimal getJuros() {
        return this.juros;
    }
    
    public void setJuros(BigDecimal juros) {
        this.juros = juros;
    }




}


