package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conta generated by hbm2java
 */
public class Conta  implements java.io.Serializable {


     private int idconta;
     private Usuario usuario;
     private String descricao;
     private Character flagPadrao;
     private String observacaoEntrada;
     private String observacaoSaida;
     private Date dataInclusao;
     private Boolean flagAtivo;
     private Set lancamentoCaixas = new HashSet(0);

    public Conta() {
    }

	
    public Conta(int idconta) {
        this.idconta = idconta;
    }
    public Conta(int idconta, Usuario usuario, String descricao, Character flagPadrao, String observacaoEntrada, String observacaoSaida, Date dataInclusao, Boolean flagAtivo, Set lancamentoCaixas) {
       this.idconta = idconta;
       this.usuario = usuario;
       this.descricao = descricao;
       this.flagPadrao = flagPadrao;
       this.observacaoEntrada = observacaoEntrada;
       this.observacaoSaida = observacaoSaida;
       this.dataInclusao = dataInclusao;
       this.flagAtivo = flagAtivo;
       this.lancamentoCaixas = lancamentoCaixas;
    }
   
    public int getIdconta() {
        return this.idconta;
    }
    
    public void setIdconta(int idconta) {
        this.idconta = idconta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Character getFlagPadrao() {
        return this.flagPadrao;
    }
    
    public void setFlagPadrao(Character flagPadrao) {
        this.flagPadrao = flagPadrao;
    }
    public String getObservacaoEntrada() {
        return this.observacaoEntrada;
    }
    
    public void setObservacaoEntrada(String observacaoEntrada) {
        this.observacaoEntrada = observacaoEntrada;
    }
    public String getObservacaoSaida() {
        return this.observacaoSaida;
    }
    
    public void setObservacaoSaida(String observacaoSaida) {
        this.observacaoSaida = observacaoSaida;
    }
    public Date getDataInclusao() {
        return this.dataInclusao;
    }
    
    public void setDataInclusao(Date dataInclusao) {
        this.dataInclusao = dataInclusao;
    }
    public Boolean getFlagAtivo() {
        return this.flagAtivo;
    }
    
    public void setFlagAtivo(Boolean flagAtivo) {
        this.flagAtivo = flagAtivo;
    }
    public Set getLancamentoCaixas() {
        return this.lancamentoCaixas;
    }
    
    public void setLancamentoCaixas(Set lancamentoCaixas) {
        this.lancamentoCaixas = lancamentoCaixas;
    }




}


