package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LancamentoCaixaId generated by hbm2java
 */
public class LancamentoCaixaId  implements java.io.Serializable {


     private int idempresa;
     private Date dataLancamento;
     private int idlancamento;

    public LancamentoCaixaId() {
    }

    public LancamentoCaixaId(int idempresa, Date dataLancamento, int idlancamento) {
       this.idempresa = idempresa;
       this.dataLancamento = dataLancamento;
       this.idlancamento = idlancamento;
    }
   
    public int getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public Date getDataLancamento() {
        return this.dataLancamento;
    }
    
    public void setDataLancamento(Date dataLancamento) {
        this.dataLancamento = dataLancamento;
    }
    public int getIdlancamento() {
        return this.idlancamento;
    }
    
    public void setIdlancamento(int idlancamento) {
        this.idlancamento = idlancamento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LancamentoCaixaId) ) return false;
		 LancamentoCaixaId castOther = ( LancamentoCaixaId ) other; 
         
		 return (this.getIdempresa()==castOther.getIdempresa())
 && ( (this.getDataLancamento()==castOther.getDataLancamento()) || ( this.getDataLancamento()!=null && castOther.getDataLancamento()!=null && this.getDataLancamento().equals(castOther.getDataLancamento()) ) )
 && (this.getIdlancamento()==castOther.getIdlancamento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdempresa();
         result = 37 * result + ( getDataLancamento() == null ? 0 : this.getDataLancamento().hashCode() );
         result = 37 * result + this.getIdlancamento();
         return result;
   }   


}


