package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * LancamentoCaixa generated by hbm2java
 */
public class LancamentoCaixa  implements java.io.Serializable {


     private LancamentoCaixaId id;
     private Conta conta;
     private Usuario usuario;
     private char flagMovimento;
     private BigDecimal valor;
     private String observacao;
     private Date dataInclusao;

    public LancamentoCaixa() {
    }

	
    public LancamentoCaixa(LancamentoCaixaId id, Conta conta, char flagMovimento) {
        this.id = id;
        this.conta = conta;
        this.flagMovimento = flagMovimento;
    }
    public LancamentoCaixa(LancamentoCaixaId id, Conta conta, Usuario usuario, char flagMovimento, BigDecimal valor, String observacao, Date dataInclusao) {
       this.id = id;
       this.conta = conta;
       this.usuario = usuario;
       this.flagMovimento = flagMovimento;
       this.valor = valor;
       this.observacao = observacao;
       this.dataInclusao = dataInclusao;
    }
   
    public LancamentoCaixaId getId() {
        return this.id;
    }
    
    public void setId(LancamentoCaixaId id) {
        this.id = id;
    }
    public Conta getConta() {
        return this.conta;
    }
    
    public void setConta(Conta conta) {
        this.conta = conta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public char getFlagMovimento() {
        return this.flagMovimento;
    }
    
    public void setFlagMovimento(char flagMovimento) {
        this.flagMovimento = flagMovimento;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Date getDataInclusao() {
        return this.dataInclusao;
    }
    
    public void setDataInclusao(Date dataInclusao) {
        this.dataInclusao = dataInclusao;
    }




}


