package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer idProduto;
     private Usuario usuario;
     private UnidadeMedida unidadeMedida;
     private String descricao;
     private Float peso;
     private Date dataInclusao;
     private boolean flagAtivo;
     private String classificacao;

    public Produto() {
    }

	
    public Produto(UnidadeMedida unidadeMedida, boolean flagAtivo) {
        this.unidadeMedida = unidadeMedida;
        this.flagAtivo = flagAtivo;
    }
    public Produto(Usuario usuario, UnidadeMedida unidadeMedida, String descricao, Float peso, Date dataInclusao, boolean flagAtivo, String classificacao) {
       this.usuario = usuario;
       this.unidadeMedida = unidadeMedida;
       this.descricao = descricao;
       this.peso = peso;
       this.dataInclusao = dataInclusao;
       this.flagAtivo = flagAtivo;
       this.classificacao = classificacao;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public UnidadeMedida getUnidadeMedida() {
        return this.unidadeMedida;
    }
    
    public void setUnidadeMedida(UnidadeMedida unidadeMedida) {
        this.unidadeMedida = unidadeMedida;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Float getPeso() {
        return this.peso;
    }
    
    public void setPeso(Float peso) {
        this.peso = peso;
    }
    public Date getDataInclusao() {
        return this.dataInclusao;
    }
    
    public void setDataInclusao(Date dataInclusao) {
        this.dataInclusao = dataInclusao;
    }
    public boolean isFlagAtivo() {
        return this.flagAtivo;
    }
    
    public void setFlagAtivo(boolean flagAtivo) {
        this.flagAtivo = flagAtivo;
    }
    public String getClassificacao() {
        return this.classificacao;
    }
    
    public void setClassificacao(String classificacao) {
        this.classificacao = classificacao;
    }




}


