package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SaldoCaixaId generated by hbm2java
 */
public class SaldoCaixaId  implements java.io.Serializable {


     private int idempresa;
     private Date dataSaldo;

    public SaldoCaixaId() {
    }

    public SaldoCaixaId(int idempresa, Date dataSaldo) {
       this.idempresa = idempresa;
       this.dataSaldo = dataSaldo;
    }
   
    public int getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public Date getDataSaldo() {
        return this.dataSaldo;
    }
    
    public void setDataSaldo(Date dataSaldo) {
        this.dataSaldo = dataSaldo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SaldoCaixaId) ) return false;
		 SaldoCaixaId castOther = ( SaldoCaixaId ) other; 
         
		 return (this.getIdempresa()==castOther.getIdempresa())
 && ( (this.getDataSaldo()==castOther.getDataSaldo()) || ( this.getDataSaldo()!=null && castOther.getDataSaldo()!=null && this.getDataSaldo().equals(castOther.getDataSaldo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdempresa();
         result = 37 * result + ( getDataSaldo() == null ? 0 : this.getDataSaldo().hashCode() );
         return result;
   }   


}


