package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * SaldoCaixa generated by hbm2java
 */
public class SaldoCaixa  implements java.io.Serializable {


     private SaldoCaixaId id;
     private Correntista correntista;
     private BigDecimal valor;

    public SaldoCaixa() {
    }

	
    public SaldoCaixa(SaldoCaixaId id, Correntista correntista) {
        this.id = id;
        this.correntista = correntista;
    }
    public SaldoCaixa(SaldoCaixaId id, Correntista correntista, BigDecimal valor) {
       this.id = id;
       this.correntista = correntista;
       this.valor = valor;
    }
   
    public SaldoCaixaId getId() {
        return this.id;
    }
    
    public void setId(SaldoCaixaId id) {
        this.id = id;
    }
    public Correntista getCorrentista() {
        return this.correntista;
    }
    
    public void setCorrentista(Correntista correntista) {
        this.correntista = correntista;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


