package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TamanhoPneu generated by hbm2java
 */
public class TamanhoPneu  implements java.io.Serializable {


     private Integer idtamanhopneu;
     private Usuario usuario;
     private String descricao;
     private Date dataInclusao;
     private Set pneus = new HashSet(0);

    public TamanhoPneu() {
    }

    public TamanhoPneu(Usuario usuario, String descricao, Date dataInclusao, Set pneus) {
       this.usuario = usuario;
       this.descricao = descricao;
       this.dataInclusao = dataInclusao;
       this.pneus = pneus;
    }
   
    public Integer getIdtamanhopneu() {
        return this.idtamanhopneu;
    }
    
    public void setIdtamanhopneu(Integer idtamanhopneu) {
        this.idtamanhopneu = idtamanhopneu;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDataInclusao() {
        return this.dataInclusao;
    }
    
    public void setDataInclusao(Date dataInclusao) {
        this.dataInclusao = dataInclusao;
    }
    public Set getPneus() {
        return this.pneus;
    }
    
    public void setPneus(Set pneus) {
        this.pneus = pneus;
    }




}


