package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TituloPagar generated by hbm2java
 */
public class TituloPagar  implements java.io.Serializable {


     private TituloPagarId id;
     private Correntista correntista;
     private TipoTitulo tipoTitulo;
     private Usuario usuario;
     private Date dataEmissao;
     private Date dataVencimento;
     private BigDecimal valor;
     private BigDecimal valorPago;
     private BigDecimal juros;
     private String observacao;
     private Date dataInclusao;
     private Date dataPagamento;
     private Set baixaPagars = new HashSet(0);

    public TituloPagar() {
    }

	
    public TituloPagar(TituloPagarId id, Correntista correntista, TipoTitulo tipoTitulo) {
        this.id = id;
        this.correntista = correntista;
        this.tipoTitulo = tipoTitulo;
    }
    public TituloPagar(TituloPagarId id, Correntista correntista, TipoTitulo tipoTitulo, Usuario usuario, Date dataEmissao, Date dataVencimento, BigDecimal valor, BigDecimal valorPago, BigDecimal juros, String observacao, Date dataInclusao, Date dataPagamento, Set baixaPagars) {
       this.id = id;
       this.correntista = correntista;
       this.tipoTitulo = tipoTitulo;
       this.usuario = usuario;
       this.dataEmissao = dataEmissao;
       this.dataVencimento = dataVencimento;
       this.valor = valor;
       this.valorPago = valorPago;
       this.juros = juros;
       this.observacao = observacao;
       this.dataInclusao = dataInclusao;
       this.dataPagamento = dataPagamento;
       this.baixaPagars = baixaPagars;
    }
   
    public TituloPagarId getId() {
        return this.id;
    }
    
    public void setId(TituloPagarId id) {
        this.id = id;
    }
    public Correntista getCorrentista() {
        return this.correntista;
    }
    
    public void setCorrentista(Correntista correntista) {
        this.correntista = correntista;
    }
    public TipoTitulo getTipoTitulo() {
        return this.tipoTitulo;
    }
    
    public void setTipoTitulo(TipoTitulo tipoTitulo) {
        this.tipoTitulo = tipoTitulo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getDataEmissao() {
        return this.dataEmissao;
    }
    
    public void setDataEmissao(Date dataEmissao) {
        this.dataEmissao = dataEmissao;
    }
    public Date getDataVencimento() {
        return this.dataVencimento;
    }
    
    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }
    public BigDecimal getJuros() {
        return this.juros;
    }
    
    public void setJuros(BigDecimal juros) {
        this.juros = juros;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Date getDataInclusao() {
        return this.dataInclusao;
    }
    
    public void setDataInclusao(Date dataInclusao) {
        this.dataInclusao = dataInclusao;
    }
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }
    public Set getBaixaPagars() {
        return this.baixaPagars;
    }
    
    public void setBaixaPagars(Set baixaPagars) {
        this.baixaPagars = baixaPagars;
    }




}


