package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA



/**
 * TituloPagarId generated by hbm2java
 */
public class TituloPagarId  implements java.io.Serializable {


     private int numero;
     private int parcela;
     private int idcorrentista;
     private int idtipotitulo;

    public TituloPagarId() {
    }

    public TituloPagarId(int numero, int parcela, int idcorrentista, int idtipotitulo) {
       this.numero = numero;
       this.parcela = parcela;
       this.idcorrentista = idcorrentista;
       this.idtipotitulo = idtipotitulo;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public int getParcela() {
        return this.parcela;
    }
    
    public void setParcela(int parcela) {
        this.parcela = parcela;
    }
    public int getIdcorrentista() {
        return this.idcorrentista;
    }
    
    public void setIdcorrentista(int idcorrentista) {
        this.idcorrentista = idcorrentista;
    }
    public int getIdtipotitulo() {
        return this.idtipotitulo;
    }
    
    public void setIdtipotitulo(int idtipotitulo) {
        this.idtipotitulo = idtipotitulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TituloPagarId) ) return false;
		 TituloPagarId castOther = ( TituloPagarId ) other; 
         
		 return (this.getNumero()==castOther.getNumero())
 && (this.getParcela()==castOther.getParcela())
 && (this.getIdcorrentista()==castOther.getIdcorrentista())
 && (this.getIdtipotitulo()==castOther.getIdtipotitulo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumero();
         result = 37 * result + this.getParcela();
         result = 37 * result + this.getIdcorrentista();
         result = 37 * result + this.getIdtipotitulo();
         return result;
   }   


}


