package erp.modelos.banco;
// Generated 19/04/2012 16:50:13 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TituloReceber generated by hbm2java
 */
public class TituloReceber implements java.io.Serializable {

    private TituloReceberId id;
    private Correntista correntista;
    private TipoTitulo tipoTitulo;
    private Usuario usuario;
    private Date dataEmissao;
    private Date dataVencimento;
    private BigDecimal valor;
    private BigDecimal valorPago;
    private BigDecimal juros;
    private Date dataInclusao;
    private String observacao;
    private Correntista idfinanceira;
    private Date dataPagamento;
    private Set baixaRecebers = new HashSet(0);

    public Date getDataPagamento() {
        return dataPagamento;
    }

    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }

    public Correntista getIdfinanceira() {
        return idfinanceira;
    }

    public void setIdfinanceira(Correntista idfinanceira) {
        this.idfinanceira = idfinanceira;
    }

    public TituloReceber() {
    }

    public TituloReceber(TituloReceberId id, Correntista correntista, TipoTitulo tipoTitulo) {
        this.id = id;
        this.correntista = correntista;
        this.tipoTitulo = tipoTitulo;
    }

    public TituloReceber(TituloReceberId id, Correntista correntista, TipoTitulo tipoTitulo, Usuario usuario, Date dataEmissao, Date dataVencimento, BigDecimal valor, BigDecimal valorPago, BigDecimal juros, Date dataInclusao, String observacao,Date dataPagamento, Correntista idfinanceira, Set baixaRecebers) {
        this.id = id;
        this.correntista = correntista;
        this.tipoTitulo = tipoTitulo;
        this.usuario = usuario;
        this.dataEmissao = dataEmissao;
        this.dataVencimento = dataVencimento;
        this.valor = valor;
        this.valorPago = valorPago;
        this.juros = juros;
        this.dataInclusao = dataInclusao;
        this.observacao = observacao;
        this.dataPagamento = dataPagamento;
        this.idfinanceira = idfinanceira;
        this.baixaRecebers = baixaRecebers;
    }

    public TituloReceberId getId() {
        return this.id;
    }

    public void setId(TituloReceberId id) {
        this.id = id;
    }

    public Correntista getCorrentista() {
        return this.correntista;
    }

    public void setCorrentista(Correntista correntista) {
        this.correntista = correntista;
    }

    public TipoTitulo getTipoTitulo() {
        return this.tipoTitulo;
    }

    public void setTipoTitulo(TipoTitulo tipoTitulo) {
        this.tipoTitulo = tipoTitulo;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Date getDataEmissao() {
        return this.dataEmissao;
    }

    public void setDataEmissao(Date dataEmissao) {
        this.dataEmissao = dataEmissao;
    }

    public Date getDataVencimento() {
        return this.dataVencimento;
    }

    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }

    public BigDecimal getValor() {
        return this.valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    public BigDecimal getValorPago() {
        return this.valorPago;
    }

    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }

    public BigDecimal getJuros() {
        return this.juros;
    }

    public void setJuros(BigDecimal juros) {
        this.juros = juros;
    }

    public Date getDataInclusao() {
        return this.dataInclusao;
    }

    public void setDataInclusao(Date dataInclusao) {
        this.dataInclusao = dataInclusao;
    }

    public String getObservacao() {
        return this.observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    public Set getBaixaRecebers() {
        return this.baixaRecebers;
    }

    public void setBaixaRecebers(Set baixaRecebers) {
        this.baixaRecebers = baixaRecebers;
    }
}
