package erp.modelos.banco;
// Generated 24/09/2013 17:05:52 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nome;
     private Date dataInclusao;
     private Boolean flagAtivo;
     private String senha;
     private Set baixaPagars = new HashSet(0);
     private Set contas = new HashSet(0);
     private Set tipoPagamentos = new HashSet(0);
     private Set pneus = new HashSet(0);
     private Set correntistas = new HashSet(0);
     private Set lancamentoCaixas = new HashSet(0);
     private Set marcas = new HashSet(0);
     private Set unidadeMedidas = new HashSet(0);
     private Set tituloRecebers = new HashSet(0);
     private Set tipoTitulos = new HashSet(0);
     private Set tamanhoPneus = new HashSet(0);
     private Set produtos = new HashSet(0);
     private Set tituloPagars = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nome, Date dataInclusao, Boolean flagAtivo, String senha, Set baixaPagars, Set contas, Set tipoPagamentos, Set pneus, Set correntistas, Set lancamentoCaixas, Set marcas, Set unidadeMedidas, Set tituloRecebers, Set tipoTitulos, Set tamanhoPneus, Set produtos, Set tituloPagars) {
       this.nome = nome;
       this.dataInclusao = dataInclusao;
       this.flagAtivo = flagAtivo;
       this.senha = senha;
       this.baixaPagars = baixaPagars;
       this.contas = contas;
       this.tipoPagamentos = tipoPagamentos;
       this.pneus = pneus;
       this.correntistas = correntistas;
       this.lancamentoCaixas = lancamentoCaixas;
       this.marcas = marcas;
       this.unidadeMedidas = unidadeMedidas;
       this.tituloRecebers = tituloRecebers;
       this.tipoTitulos = tipoTitulos;
       this.tamanhoPneus = tamanhoPneus;
       this.produtos = produtos;
       this.tituloPagars = tituloPagars;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataInclusao() {
        return this.dataInclusao;
    }
    
    public void setDataInclusao(Date dataInclusao) {
        this.dataInclusao = dataInclusao;
    }
    public Boolean getFlagAtivo() {
        return this.flagAtivo;
    }
    
    public void setFlagAtivo(Boolean flagAtivo) {
        this.flagAtivo = flagAtivo;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getBaixaPagars() {
        return this.baixaPagars;
    }
    
    public void setBaixaPagars(Set baixaPagars) {
        this.baixaPagars = baixaPagars;
    }
    public Set getContas() {
        return this.contas;
    }
    
    public void setContas(Set contas) {
        this.contas = contas;
    }
    public Set getTipoPagamentos() {
        return this.tipoPagamentos;
    }
    
    public void setTipoPagamentos(Set tipoPagamentos) {
        this.tipoPagamentos = tipoPagamentos;
    }
    public Set getPneus() {
        return this.pneus;
    }
    
    public void setPneus(Set pneus) {
        this.pneus = pneus;
    }
    public Set getCorrentistas() {
        return this.correntistas;
    }
    
    public void setCorrentistas(Set correntistas) {
        this.correntistas = correntistas;
    }
    public Set getLancamentoCaixas() {
        return this.lancamentoCaixas;
    }
    
    public void setLancamentoCaixas(Set lancamentoCaixas) {
        this.lancamentoCaixas = lancamentoCaixas;
    }
    public Set getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Set marcas) {
        this.marcas = marcas;
    }
    public Set getUnidadeMedidas() {
        return this.unidadeMedidas;
    }
    
    public void setUnidadeMedidas(Set unidadeMedidas) {
        this.unidadeMedidas = unidadeMedidas;
    }
    public Set getTituloRecebers() {
        return this.tituloRecebers;
    }
    
    public void setTituloRecebers(Set tituloRecebers) {
        this.tituloRecebers = tituloRecebers;
    }
    public Set getTipoTitulos() {
        return this.tipoTitulos;
    }
    
    public void setTipoTitulos(Set tipoTitulos) {
        this.tipoTitulos = tipoTitulos;
    }
    public Set getTamanhoPneus() {
        return this.tamanhoPneus;
    }
    
    public void setTamanhoPneus(Set tamanhoPneus) {
        this.tamanhoPneus = tamanhoPneus;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }
    public Set getTituloPagars() {
        return this.tituloPagars;
    }
    
    public void setTituloPagars(Set tituloPagars) {
        this.tituloPagars = tituloPagars;
    }




}


