package erp.visoes.cadastro;

import erp.controles.CFrame;
import erp.controles.cadastro.CTipoTitulo;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;

/**
 * @author Arthur
 */
public class VTipoTitulo extends javax.swing.JInternalFrame {

    CTipoTitulo controle;
    
    public VTipoTitulo() {
        initComponents();

        controle = new CTipoTitulo();       
        
        CFrame.configuraAtalhoCampo(idtipotitulo, btnPesq, KeyEvent.VK_F3, JComponent.WHEN_FOCUSED);
        
        CFrame.configuraAtalhoBotao(btnSalva, KeyEvent.VK_F5, JComponent.WHEN_IN_FOCUSED_WINDOW);

        CFrame.configuraAtalhoBotao(btnCancela, KeyEvent.VK_F8, JComponent.WHEN_IN_FOCUSED_WINDOW);
        
        CFrame.configuraAtalhoBotao(btnExclui, KeyEvent.VK_F9, JComponent.WHEN_IN_FOCUSED_WINDOW);
        
        CFrame.configuraAtalhoFecharVisao(this,KeyEvent.VK_ESCAPE, JComponent.WHEN_IN_FOCUSED_WINDOW);           
                
        CFrame.acaoEnter(btnPesq);
        CFrame.acaoEnter(btnSalva);
        CFrame.acaoEnter(btnCancela);
        CFrame.acaoEnter(btnExclui);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExclui = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        idtipotitulo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnPesq = new javax.swing.JButton();
        descricao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        flagReceber = new javax.swing.JCheckBox();
        flagPagar = new javax.swing.JCheckBox();
        flagAtivo = new javax.swing.JCheckBox();
        flagGeraNumero = new javax.swing.JCheckBox();
        flagGeraduplicata = new javax.swing.JCheckBox();
        flagGerapromissoria = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tipo de Título");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnExclui.setText("Excluir (F9)");
        btnExclui.setName("btnExclui"); // NOI18N
        btnExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancelar (F8)");
        btnCancela.setName("btnCancela"); // NOI18N
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        btnSalva.setText("Salvar (F5)");
        btnSalva.setName("btnSalva"); // NOI18N
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        idtipotitulo.setName("idtipotitulo");
        idtipotitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idtipotituloFocusLost(evt);
            }
        });

        jLabel12.setText("ID:");
        jLabel12.setName("jLabel12");

        btnPesq.setText("Pesquisa (F3)");
        btnPesq.setFocusable(false);
        btnPesq.setName("btnPesq");
        btnPesq.setRequestFocusEnabled(false);
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        descricao.setName("descricao");

        jLabel10.setText("Descrição:");
        jLabel10.setName("jLabel10"); // NOI18N

        flagReceber.setText("Receber");
        flagReceber.setName("flagReceber");

        flagPagar.setText("Pagar");
        flagPagar.setName("flagPagar");

        flagAtivo.setSelected(true);
        flagAtivo.setText("Ativo");
        flagAtivo.setName("flagAtivo");

        flagGeraNumero.setText("Gera novo número");
        flagGeraNumero.setName("flagGeraNumero");

        flagGeraduplicata.setText("Gera Duplicata");
        flagGeraduplicata.setName("flagGeraduplicata");

        flagGerapromissoria.setText("Gera Promissória");
        flagGerapromissoria.setName("flagGerapromissoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(flagReceber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(flagPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                .addComponent(flagAtivo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(flagGeraNumero)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idtipotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesq)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(flagGeraduplicata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(flagGerapromissoria))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExclui)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancela)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalva)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(idtipotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flagReceber)
                    .addComponent(flagPagar)
                    .addComponent(flagAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flagGeraNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flagGeraduplicata)
                    .addComponent(flagGerapromissoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExclui)
                    .addComponent(btnSalva)
                    .addComponent(btnCancela))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiActionPerformed
        controle.exclui(this);
}//GEN-LAST:event_btnExcluiActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        controle.cancela(this);
}//GEN-LAST:event_btnCancelaActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        controle.salva(this);
}//GEN-LAST:event_btnSalvaActionPerformed

    private void idtipotituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idtipotituloFocusLost
        controle.criticaId(this);
    }//GEN-LAST:event_idtipotituloFocusLost

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        controle.pesquisa(this);
    }//GEN-LAST:event_btnPesqActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        CFrame.fechaVisao(CFrame.VISOES.TIPO_TITULO);
    }//GEN-LAST:event_formInternalFrameClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnExclui;
    private javax.swing.JButton btnPesq;
    private javax.swing.JButton btnSalva;
    private javax.swing.JTextField descricao;
    private javax.swing.JCheckBox flagAtivo;
    private javax.swing.JCheckBox flagGeraNumero;
    private javax.swing.JCheckBox flagGeraduplicata;
    private javax.swing.JCheckBox flagGerapromissoria;
    private javax.swing.JCheckBox flagPagar;
    private javax.swing.JCheckBox flagReceber;
    private javax.swing.JTextField idtipotitulo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    // End of variables declaration//GEN-END:variables
}
