package erp.visoes;

import erp.controles.CConfiguracoes;
import erp.controles.CFrame;
import erp.controles.CFrame.VISOES;
import erp.util.HibernateUtil;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.SplashScreen;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.hibernate.Session;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */

/*
 * VFrame.java
 *
 * Created on 10/05/2011, 14:28:23
 */
/**
 *
 * @author Cliente
 */
public class VFrameNovo extends javax.swing.JFrame {

    /**
     * Creates new form VFrame
     */
    public VFrameNovo() {
        initComponents();

        this.setTitle("ERP Carga Pesada");

        Set<AWTKeyStroke> forwardKeys = new HashSet<AWTKeyStroke>(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        forwardKeys.add(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, forwardKeys);

        CFrame.configuraAtalhoFecharFrame(this, KeyEvent.VK_ESCAPE, JComponent.WHEN_IN_FOCUSED_WINDOW);

        CFrame.setUsuario(1);
        CFrame.setFrame(this);
        jToolCadastros.setVisible(false);
        jToolReceber.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupUniao = new javax.swing.JPopupMenu();
        jMenuConfiguracao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSair = new javax.swing.JMenuItem();
        buttonGroupToolBar = new javax.swing.ButtonGroup();
        popupCadReceber = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        popupMovReceber = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        popupCadCadastro = new javax.swing.JPopupMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        popupRelReceber = new javax.swing.JPopupMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        UniaoBtn = new javax.swing.JButton();
        jToolPrincipal = new javax.swing.JToolBar();
        jButtonCadastros = new javax.swing.JToggleButton();
        jButtonReceber = new javax.swing.JToggleButton();
        jToolReceber = new javax.swing.JToolBar();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jToolCadastros = new javax.swing.JToolBar();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        popupUniao.setName("popupUniao");

        jMenuConfiguracao.setMnemonic('C');
        jMenuConfiguracao.setText("Configuração");
        jMenuConfiguracao.setName("jConfig");
        jMenuConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConfiguracaoActionPerformed(evt);
            }
        });
        popupUniao.add(jMenuConfiguracao);

        jSeparator1.setName("jSeparator1");
        popupUniao.add(jSeparator1);

        jMenuSair.setMnemonic('S');
        jMenuSair.setText("Sair");
        jMenuSair.setName("jMenuSair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        popupUniao.add(jMenuSair);

        popupCadReceber.setName("popupCadReceber");

        jMenuItem1.setMnemonic('l');
        jMenuItem1.setText("Cliente");
        jMenuItem1.setName("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        popupCadReceber.add(jMenuItem1);

        jMenuItem2.setMnemonic('T');
        jMenuItem2.setText("Tipo de Título");
        jMenuItem2.setName("jMenuItem2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        popupCadReceber.add(jMenuItem2);

        jMenuItem3.setMnemonic('i');
        jMenuItem3.setText("Tipo de Pagamento");
        jMenuItem3.setToolTipText("");
        jMenuItem3.setName("jMenuItem3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        popupCadReceber.add(jMenuItem3);

        popupMovReceber.setName("popupMovReceber");

        jMenuItem4.setMnemonic('T');
        jMenuItem4.setText("Título Receber");
        jMenuItem4.setName("jMenuItem4");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        popupMovReceber.add(jMenuItem4);

        jMenuItem5.setMnemonic('B');
        jMenuItem5.setText("Baixa de Título");
        jMenuItem5.setName("jMenuItem5");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        popupMovReceber.add(jMenuItem5);

        popupCadCadastro.setName("popupCadCadastro");

        jMenuItem6.setMnemonic('o');
        jMenuItem6.setText("Correntista");
        jMenuItem6.setName("jMenuItem6");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        popupCadCadastro.add(jMenuItem6);

        jMenuItem7.setMnemonic('T');
        jMenuItem7.setText("Tipo de Título");
        jMenuItem7.setName("jMenuItem7");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        popupCadCadastro.add(jMenuItem7);

        jMenuItem8.setMnemonic('i');
        jMenuItem8.setText("Tipo de Pagamento");
        jMenuItem8.setToolTipText("");
        jMenuItem8.setName("jMenuItem8");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        popupCadCadastro.add(jMenuItem8);

        popupRelReceber.setName("popupRelReceber");

        jMenuItem9.setText("Duplicata");
        jMenuItem9.setName("jMenuItem9");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        popupRelReceber.add(jMenuItem9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("União ERP");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(statusMessageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusAnimationLabel))
                    .addComponent(statusPanelSeparator))
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jPanel1.setName("jPanel1"); // NOI18N

        jDesktopPane1.setName("jDesktopPane1"); // NOI18N

        UniaoBtn.setText("União ERP");
        UniaoBtn.setFocusable(false);
        UniaoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UniaoBtn.setName("UniaoBtn");
        UniaoBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        UniaoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniaoBtnActionPerformed(evt);
            }
        });

        jToolPrincipal.setFloatable(false);
        jToolPrincipal.setRollover(true);
        jToolPrincipal.setName("jToolPrincipal");

        buttonGroupToolBar.add(jButtonCadastros);
        jButtonCadastros.setMnemonic('C');
        jButtonCadastros.setText("Cadastros");
        jButtonCadastros.setFocusable(false);
        jButtonCadastros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastros.setName("jButtonCadastros");
        jButtonCadastros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrosActionPerformed(evt);
            }
        });
        jToolPrincipal.add(jButtonCadastros);

        buttonGroupToolBar.add(jButtonReceber);
        jButtonReceber.setMnemonic('R');
        jButtonReceber.setText("Receber");
        jButtonReceber.setFocusable(false);
        jButtonReceber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReceber.setName("jButtonReceber");
        jButtonReceber.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceberActionPerformed(evt);
            }
        });
        jToolPrincipal.add(jButtonReceber);

        jToolReceber.setFloatable(false);
        jToolReceber.setRollover(true);
        jToolReceber.setName("jToolReceber");

        jButton5.setMnemonic('a');
        jButton5.setText("Cadastros");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setName("jButton5");
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolReceber.add(jButton5);

        jButton6.setMnemonic('M');
        jButton6.setText("Movimentação");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setName("jButton6");
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolReceber.add(jButton6);

        jButton7.setText("Consultas");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setName("jButton7");
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolReceber.add(jButton7);

        jButton8.setText("Relatórios");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setName("jButton8");
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolReceber.add(jButton8);

        jToolCadastros.setFloatable(false);
        jToolCadastros.setRollover(true);
        jToolCadastros.setName("jToolCadastros");

        jButton9.setMnemonic('a');
        jButton9.setText("Cadastros");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setName("jButton9");
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolCadastros.add(jButton9);

        jButton11.setText("Consultas");
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setName("jButton11");
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolCadastros.add(jButton11);

        jButton12.setText("Relatórios");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setName("jButton12");
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolCadastros.add(jButton12);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(UniaoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE))
            .addComponent(jDesktopPane1)
            .addComponent(jToolReceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolCadastros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UniaoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jToolPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UniaoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniaoBtnActionPerformed
        popupUniao.show(UniaoBtn, 0, UniaoBtn.getHeight());
    }//GEN-LAST:event_UniaoBtnActionPerformed

    private void jMenuConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConfiguracaoActionPerformed
        CFrame.abreVisao(VISOES.CONFIGURACOES, jDesktopPane1);
    }//GEN-LAST:event_jMenuConfiguracaoActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
    }//GEN-LAST:event_formWindowStateChanged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jToolReceber.setSize(jDesktopPane1.getWidth(), jToolReceber.getHeight());
    }//GEN-LAST:event_formComponentResized

    private void jButtonCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrosActionPerformed
        jGrupButtonChanged();
    }//GEN-LAST:event_jButtonCadastrosActionPerformed

    private void jButtonReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceberActionPerformed
        jGrupButtonChanged();
    }//GEN-LAST:event_jButtonReceberActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        popupCadReceber.show(jButton5, 0, jToolReceber.getHeight());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CFrame.abreVisao(VISOES.CORRENTISTA, jDesktopPane1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CFrame.abreVisao(VISOES.TIPO_TITULO, jDesktopPane1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CFrame.abreVisao(VISOES.TIPO_PAGAMENTO, jDesktopPane1);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CFrame.abreVisao(VISOES.TITULO_RECEBER, jDesktopPane1);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CFrame.abreVisao(VISOES.BAIXA_RECEBER, jDesktopPane1);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        popupMovReceber.show(jButton6, jButton5.getX(), jToolReceber.getHeight());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
         CFrame.abreVisao(VISOES.CORRENTISTA, jDesktopPane1);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
          CFrame.abreVisao(VISOES.TIPO_TITULO, jDesktopPane1);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        CFrame.abreVisao(VISOES.TIPO_PAGAMENTO, jDesktopPane1);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        popupCadCadastro.show(jButton9, 0, jToolCadastros.getHeight());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        popupRelReceber.show(jButton8, jButton7.getX(), jToolReceber.getHeight());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        CFrame.abreVisao(VISOES.DUPLICATA_RECEBER, jDesktopPane1);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jGrupButtonChanged() {
        jToolCadastros.setVisible(buttonGroupToolBar.isSelected(jButtonCadastros.getModel()));
        jToolReceber.setVisible(buttonGroupToolBar.isSelected(jButtonReceber.getModel()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UniaoBtn;
    private javax.swing.ButtonGroup buttonGroupToolBar;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JToggleButton jButtonCadastros;
    private javax.swing.JToggleButton jButtonReceber;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuConfiguracao;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolCadastros;
    private javax.swing.JToolBar jToolPrincipal;
    private javax.swing.JToolBar jToolReceber;
    private javax.swing.JPopupMenu popupCadCadastro;
    private javax.swing.JPopupMenu popupCadReceber;
    private javax.swing.JPopupMenu popupMovReceber;
    private javax.swing.JPopupMenu popupRelReceber;
    private javax.swing.JPopupMenu popupUniao;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables
}
