/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJDialog.java
 *
 * Created on 15/05/2011, 11:04:47
 */
package erp.visoes;

import erp.controles.CFrame;
import erp.util.TableModelPadrao;
import java.awt.FontMetrics;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.regex.PatternSyntaxException;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Arthur
 */
public class VPesquisa extends javax.swing.JDialog {

    private Object resultado = null;
    private TableRowSorter<TableModel> sorter = null;
    private CFrame.VISOES tela = null;

    /**
     * Creates new form NewJDialog
     */
    public VPesquisa(java.awt.Frame parent, String titulo, boolean modal) {
        super(parent, titulo, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        jTable1.setCellSelectionEnabled(false);
        jTable1.setRowSelectionAllowed(true);
        filterText.requestFocus();
        CFrame.configuraAtalhoBotao(btnCancela, KeyEvent.VK_ESCAPE, JComponent.WHEN_IN_FOCUSED_WINDOW);
        CFrame.configuraAtalhoBotao(btnNovo, KeyEvent.VK_INSERT, JComponent.WHEN_IN_FOCUSED_WINDOW);
        btnNovo.setEnabled(false);
        this.tela = null;
    }
    
    public VPesquisa(java.awt.Frame parent, String titulo, boolean modal,CFrame.VISOES tela) {
        this(parent, titulo, modal);
        this.tela = tela;
        btnNovo.setEnabled(true);
    }    

    public Object getResultado() {
        //setResultado();
        return resultado;
    }

    public void setResultado() {
        int viewRow = jTable1.getSelectedRow();
        if (viewRow >= 0) {
            int modelRow = jTable1.convertRowIndexToModel(viewRow);
            resultado = ((TableModelPadrao) jTable1.getModel()).getLinha(modelRow);
        } else {
            resultado = null;
        }
    }

    public void setTableModel(TableModel modelo) throws Exception {
        jTable1.setModel(modelo);
        sorter = new TableRowSorter<>(modelo);
        if (modelo.getRowCount() > 0) {
            sorter.toggleSortOrder(0);
            jTable1.setRowSorter(sorter);
            jTable1.setAutoResizeMode(0);
            FontMetrics fm = jTable1.getGraphics().getFontMetrics();

            int itotal = 0;

            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                String columnName = jTable1.getColumnName(i);
                TableColumn col = jTable1.getColumnModel().getColumn(i);
                col.setPreferredWidth(fm.stringWidth(columnName) + 25);
                itotal += fm.stringWidth(columnName) + 25;
            }

            this.setSize(itotal + 48, this.getHeight());


        } else {
            JOptionPane.showMessageDialog(rootPane, "Pesquisa Vazia", "Erro", JOptionPane.ERROR_MESSAGE);
            throw new Exception();
        }
    }

    public void ordernarColuna(int Coluna) {
        sorter.toggleSortOrder(Coluna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filterText = new javax.swing.JTextField();
        btnSeleciona = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCancela = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 0));
        setModal(true);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setName("vPesquisa"); // NOI18N

        jLabel1.setText("Filtro:");
        jLabel1.setName("jLabel1"); // NOI18N

        filterText.setMinimumSize(new java.awt.Dimension(50, 20));
        filterText.setName("filterText"); // NOI18N
        filterText.setOpaque(false);
        filterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTextActionPerformed(evt);
            }
        });
        filterText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filterTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterTextKeyReleased(evt);
            }
        });

        btnSeleciona.setText("Seleciona (Enter)");
        btnSeleciona.setName("btnSeleciona"); // NOI18N
        btnSeleciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnCancela.setText("Cancela (Esc)");
        btnCancela.setName("btnCancela");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo (Insert)");
        btnNovo.setName("btnNovo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleciona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancela)
                    .addComponent(btnSeleciona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaActionPerformed
        setResultado();
        this.dispose();
    }//GEN-LAST:event_btnSelecionaActionPerformed

    private void filterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTextActionPerformed
        if (jTable1.getRowCount() == 1) {
            btnSelecionaActionPerformed(evt);
        }
    }//GEN-LAST:event_filterTextActionPerformed

    private void filterTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterTextKeyReleased

        if (KeyEvent.VK_PAGE_UP == evt.getKeyCode()||
            KeyEvent.VK_PAGE_DOWN == evt.getKeyCode()||
            KeyEvent.VK_UP == evt.getKeyCode()||
            KeyEvent.VK_DOWN == evt.getKeyCode()||
            KeyEvent.VK_ENTER == evt.getKeyCode()){
            //
        } else {
            if (filterText.getText().length() == 0) {
                sorter.setRowFilter(null);
            } else {
                try {
                    String[] textos = filterText.getText().split(" ");
                    ArrayList<RowFilter<Object, Object>> rowFilters = new ArrayList<RowFilter<Object, Object>>();
                    RowFilter<Object, Object> rowFilter;
                    for (int i = 0; i < textos.length; i++) {
                        String texto = textos[i];
                        rowFilter = RowFilter.regexFilter("(?i)" + textos[i]);
                        rowFilters.add(rowFilter);
                    }

                    RowFilter<Object, Object> filter = RowFilter.andFilter(rowFilters);
                    sorter.setRowFilter(filter);
                    jTable1.clearSelection();
                    if (jTable1.getRowCount() >= 1) {
                        jTable1.addRowSelectionInterval(0, 0);
                    }

                } catch (PatternSyntaxException pse) {
                    System.err.println("Bad regex pattern");
                }
            }
        }
    }//GEN-LAST:event_filterTextKeyReleased

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        resultado = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() > 1) {
            btnSelecionaActionPerformed(null);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void filterTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterTextKeyPressed
        if (KeyEvent.VK_PAGE_UP == evt.getKeyCode()||
            KeyEvent.VK_PAGE_DOWN == evt.getKeyCode()||
            KeyEvent.VK_UP == evt.getKeyCode()||
            KeyEvent.VK_DOWN == evt.getKeyCode()||
            KeyEvent.VK_ENTER == evt.getKeyCode()) {
            jTable1.dispatchEvent(evt);
        }
    }//GEN-LAST:event_filterTextKeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            btnSelecionaActionPerformed(null);
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        CFrame.abreVisao(tela,CFrame.getDesktopPane() );
        btnCancelaActionPerformed(null);
    }//GEN-LAST:event_btnNovoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSeleciona;
    private javax.swing.JTextField filterText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
