package erp.visoes.caixa;

import erp.controles.CFrame;
import erp.controles.cadastro.CCorrentista;
import erp.controles.caixa.CConsultaLancCaixa;
import erp.modelos.tablemodel.LancamentoCaixaCompletoTableModel;
import erp.util.ERPData;
import erp.util.ERPSelectAll;
import erp.util.ERPTable;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;

/**
 *
 * @author Arthur
 */
public class VConsultaLancCaixa extends javax.swing.JInternalFrame {

    CConsultaLancCaixa controle;


    public VConsultaLancCaixa() {
        initComponents();

        controle = new CConsultaLancCaixa();

        CFrame.configuraAtalhoCampo(idconta, btnPesq, KeyEvent.VK_F3, JComponent.WHEN_FOCUSED);

        CFrame.configuraAtalhoBotao(btnSalva, KeyEvent.VK_F5, JComponent.WHEN_IN_FOCUSED_WINDOW);

        CFrame.configuraAtalhoBotao(btnCancela, KeyEvent.VK_F8, JComponent.WHEN_IN_FOCUSED_WINDOW);

        CFrame.configuraAtalhoFecharVisao(this, KeyEvent.VK_ESCAPE, JComponent.WHEN_IN_FOCUSED_WINDOW);
        //CFrame.configuraAtalhoMaximizarVisao(this,KeyEvent.VK_F12, JComponent.WHEN_IN_FOCUSED_WINDOW);
        
        CFrame.acaoEnter(btnPesq);
        CFrame.acaoEnter(btnSalva);
        CFrame.acaoEnter(btnCancela);

        idempresa.setModel(CCorrentista.comboEmpresa());
        jTable.setModel(new LancamentoCaixaCompletoTableModel(null));
        controle.cancela(this);                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idSituac = new javax.swing.ButtonGroup();
        btnCancela = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        numero_ini = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        numero_fim = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        data_ini = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        data_fim = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        valor_ini = new javax.swing.JFormattedTextField();
        valor_fim = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        total_entrada = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        valor_saldo = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        total_saida = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        idempresa = new javax.swing.JComboBox();
        idconta = new javax.swing.JTextField();
        btnPesq = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Lançamentos do Caixa");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        btnCancela.setText("Cancelar (F8)");
        btnCancela.setName("btnCancela"); // NOI18N
        btnCancela.setRequestFocusEnabled(false);
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        btnSalva.setText("Consulta (F5)");
        btnSalva.setName("btnSalva"); // NOI18N
        btnSalva.setRequestFocusEnabled(false);
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setName("jTable");
        jScrollPane1.setViewportView(jTable);

        jLabel10.setText("Número:");
        jLabel10.setName("jLabel10"); // NOI18N

        numero_ini.setName("numero_ini");
        numero_ini.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numero_iniFocusGained(evt);
            }
        });

        jLabel11.setText("a");
        jLabel11.setName("jLabel11");

        numero_fim.setName("numero_fim");
        numero_fim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numero_fimFocusGained(evt);
            }
        });

        jLabel13.setText("Data:");
        jLabel13.setName("jLabel13");

        data_ini.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        data_ini.setName("data_ini");
        data_ini.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                data_iniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                data_iniFocusLost(evt);
            }
        });

        jLabel19.setText("a");
        jLabel19.setName("jLabel19");

        data_fim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        data_fim.setName("data_fim");
        data_fim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                data_fimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                data_fimFocusLost(evt);
            }
        });

        jLabel15.setText("Valor:");
        jLabel15.setName("jLabel15");

        valor_ini.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        valor_ini.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valor_ini.setName("valor_ini");
        valor_ini.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valor_iniFocusGained(evt);
            }
        });

        valor_fim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        valor_fim.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valor_fim.setName("valor_fim");
        valor_fim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valor_fimFocusGained(evt);
            }
        });

        jLabel21.setText("a");
        jLabel21.setName("jLabel21");

        jLabel22.setText("Quantidade:");
        jLabel22.setName("jLabel22");

        quantidade.setEditable(false);
        quantidade.setEnabled(false);
        quantidade.setName("quantidade");

        jLabel17.setText("Total Entrada:");
        jLabel17.setName("jLabel17");

        total_entrada.setEditable(false);
        total_entrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        total_entrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_entrada.setEnabled(false);
        total_entrada.setName("total_entrada");

        jLabel23.setText("Total Saída:");
        jLabel23.setName("jLabel23");

        valor_saldo.setEditable(false);
        valor_saldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        valor_saldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valor_saldo.setEnabled(false);
        valor_saldo.setName("valor_saldo");

        jLabel24.setText("Saldo:");
        jLabel24.setName("jLabel24");

        total_saida.setEditable(false);
        total_saida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        total_saida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_saida.setEnabled(false);
        total_saida.setName("total_saida");

        jLabel16.setText("Empresa");
        jLabel16.setName("jLabel16");

        idempresa.setName("idempresa");
        idempresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idempresaFocusLost(evt);
            }
        });

        idconta.setName("idconta");
        idconta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idcontaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idcontaFocusLost(evt);
            }
        });

        btnPesq.setText("Pesquisa (F3)");
        btnPesq.setFocusable(false);
        btnPesq.setName("btnPesq");
        btnPesq.setRequestFocusEnabled(false);
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        jLabel18.setText("Conta:");
        jLabel18.setName("jLabel18");

        descricao.setEnabled(false);
        descricao.setName("descricao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numero_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numero_fim, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valor_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valor_fim, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(data_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(data_fim, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(idempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idconta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descricao))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCancela)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalva))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valor_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(idempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(data_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(data_fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesq)
                    .addComponent(jLabel18)
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(numero_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(numero_fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(valor_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(valor_fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(total_saida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(total_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalva)
                    .addComponent(btnCancela))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        controle.cancela(this);
}//GEN-LAST:event_btnCancelaActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        controle.salva(this);
}//GEN-LAST:event_btnSalvaActionPerformed

    private void data_iniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_data_iniFocusGained
        SwingUtilities.invokeLater(new ERPSelectAll(data_ini));
    }//GEN-LAST:event_data_iniFocusGained

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        CFrame.fechaVisao(CFrame.VISOES.CONSULTA_LANC_CAIXA);
    }//GEN-LAST:event_formInternalFrameClosed

    private void numero_fimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numero_fimFocusGained
        numero_fim.selectAll();
    }//GEN-LAST:event_numero_fimFocusGained

    private void data_fimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_data_fimFocusGained
       SwingUtilities.invokeLater(new ERPSelectAll(data_fim));
    }//GEN-LAST:event_data_fimFocusGained

    private void numero_iniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numero_iniFocusGained
        numero_ini.selectAll();
    }//GEN-LAST:event_numero_iniFocusGained

    private void data_iniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_data_iniFocusLost
        ERPData.completaData(data_ini);
    }//GEN-LAST:event_data_iniFocusLost

    private void data_fimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_data_fimFocusLost
        ERPData.completaData(data_fim);
    }//GEN-LAST:event_data_fimFocusLost

    private void valor_iniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valor_iniFocusGained
      SwingUtilities.invokeLater(new ERPSelectAll(valor_ini));
    }//GEN-LAST:event_valor_iniFocusGained

    private void valor_fimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valor_fimFocusGained
         SwingUtilities.invokeLater(new ERPSelectAll(valor_fim));
    }//GEN-LAST:event_valor_fimFocusGained

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        ERPTable.ajustaCabecalho(jTable);
    }//GEN-LAST:event_formInternalFrameOpened

    private void idempresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idempresaFocusLost
        controle.criticaEmpresa(this);
    }//GEN-LAST:event_idempresaFocusLost

    private void idcontaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idcontaFocusGained
        idconta.selectAll();
    }//GEN-LAST:event_idcontaFocusGained

    private void idcontaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idcontaFocusLost
        controle.criticaConta(this);
    }//GEN-LAST:event_idcontaFocusLost

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        controle.pesquisaConta(this);
    }//GEN-LAST:event_btnPesqActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnPesq;
    private javax.swing.JButton btnSalva;
    private javax.swing.JFormattedTextField data_fim;
    private javax.swing.JFormattedTextField data_ini;
    private javax.swing.JTextField descricao;
    private javax.swing.ButtonGroup idSituac;
    private javax.swing.JTextField idconta;
    private javax.swing.JComboBox idempresa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField numero_fim;
    private javax.swing.JTextField numero_ini;
    private javax.swing.JTextField quantidade;
    private javax.swing.JFormattedTextField total_entrada;
    private javax.swing.JFormattedTextField total_saida;
    private javax.swing.JFormattedTextField valor_fim;
    private javax.swing.JFormattedTextField valor_ini;
    private javax.swing.JFormattedTextField valor_saldo;
    // End of variables declaration//GEN-END:variables
}
